---
title: Flumph Philosopher
name: Flumph Philosopher
baseurl: "https://flumph-philosopher.github.io"
url: "https://flumph-philosopher.github.io"
desc: Silly ramblings about old school rpgs
description: Silly ramblings about old school rpgs
about: Just another goblin in the horde
image: "https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Flumph.svg/320px-Flumph.svg.png"
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
